apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-gateway
  name: api-gateway
spec:
  type: NodePort
  ports:
    - name: "api-gateway-service"
      port: 8080
      targetPort: 8080
      nodePort: 30013
  selector:
    app: api-gateway