apiVersion: v1
kind: Service
metadata:
  labels:
    app: customers-service
  name: customers-service
spec:
  type: NodePort
  ports:
    - name: "customers-service"
      port: 8082
      targetPort: 8082
  selector:
    app: customer