apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: customer
  name: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - image: lestof/docker-spring-petclinic-customers-service
          name: customer
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
              name: customer