apiVersion: v1
kind: Service
metadata:
  labels:
    app: petclinic-bdd-service
  name: petclinic-bdd-service
spec:
  type: ClusterIP
  ports:
  - name: "petclinic-bdd-service"
    port: 3306
    targetPort: 3306
  selector:
    app: petclinic-bdd