apiVersion: v1
kind: Service
metadata:
  labels:
    app: vets-service
  name: vets-service
spec:
  type: NodePort
  ports:
    - name: "vets-service"
      port: 8083
      targetPort: 8083
  selector:
    app: vets