apiVersion: v1
kind: Service
metadata:
  labels:
    app: visits-service
  name: visits-service
spec:
  type: NodePort
  ports:
    - name: "visits-service"
      port: 8084
      targetPort: 8084
  selector:
    app: visits